### PR TITLE
Bump max version to 53

### PR DESCRIPTION
**Pull request by rbasso**

### CODE REVIEW

**Comment by rbasso** [comment]
Just a version bump, @dkearns.

**Comment by ardrabczyk** [comment]
Works for me too with Firefox 53.0.3. Judging by the lack of activity it makes me worried that fewer and fewer people are interested in `Pentadactyl` development :(

**Comment by rbasso** [comment]
> Works for me too with Firefox 53.0.3. Judging by the lack of activity it makes me worried that fewer and fewer people are interested in Pentadactyl development :(

I seems that @dkearns is the one that usually merges the PRs, but he/she has no public activity in GitHub since 2017-03-08.

**Edit**: I don't think there is lack of interest in Pentadactyl, @ardrabczyk. From the little I understand about it, it is just that there isn't much hope for it after [Firefox 57 remove support for "legacy plugins"](https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/).

**Comment by ardrabczyk** [comment]
@rbasso: Yeah, I know that and it makes me very worried. I just can't imagine using `Firefox` with a mouse without `pentadactyl`. There is a discussion going on somewhere here about `pentadactyl` future but the general conclusion is that simply there will be no `pentadactyl` for future `Firefox`. One can consider switching to `Palemoon` or keep using old versions of `Firefox` but it's not a long-term solution.

It doesn't look good.

**Pull request closed without merging**
