### PR TITLE
bump max version

### PR DESCRIPTION
**Pull request by skyhighwings**
Works fine here.

### CODE REVIEW

**Comment by skyhighwings** [comment]
dactyl no longer works in Fx 42.0.9 on beta channel — weird...

**Comment by Delapouite** [comment]
Yeah, that bump would be great!

**Comment by spetzreborn** [comment]
Verified to work.

**Comment by The-Compiler** [comment]
FWIW #95 says `:help` isn't working, but I guess that's better than not working at all :wink:

**Comment by nrb** [comment]
`:help` works for me on OS X (10.9.5) with this change.

**Comment by vyp** [comment]
@dkearns ping

**Comment by jsjohnst** [comment]
**bump**

**Comment by alexstophel** [comment]
:+1:

**Comment by skyhighwings** [comment]
I've switched away from Firefox so I can no longer vouch for the validity of this PR, but it worked when I last used it a few days ago.

**Comment by dkearns** [comment]
It's currently incompatible with 42.

If you want to ignore that you can simply disable compatibility checking.

**Pull request closed without merging**
